server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://39.105.142.63:3306/fuxiaoli_stock?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/fuxiaoli_stock?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo2018
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  rabbitmq:
    host: 118.24.211.79
    port: 5672
    username: admin
    password: admin
    virtual-host: state-service
mybatis:
  type-aliases-package: com.stock.model
  mapper-locations: classpath:mapper/*.xml
rabbit:
  queue:
    init: init.concerned.queue
xxl:
  job:
    admin:
      addresses: http://118.24.211.79:8079/xxl-job-admin
      #addresses: http://127.0.0.1:8079/xxl-job-admin
    executor:
      appname: my-data
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: