server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fuxiaoli_stock?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo2018
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  rabbitmq:
    host: 118.24.211.79
    port: 5672
    username: admin
    password: admin
    virtual-host: state-service
mybatis:
  type-aliases-package: com.stock.model
  mapper-locations: classpath:mapper/*.xml
rabbit:
  queue:
    init: init.concerned.queue