spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.0.103/stock?characterEncoding=utf-8&useSSL=false
    #username: root
    #password: 123456
    url: jdbc:mysql://127.0.0.1:3306/fuxiaoli_stock?characterEncoding=utf-8&useSSL=false
    username: root
    password: Shenghuo2018
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
